<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./static/mmoi2.glb --transform --types --draco
-->

<script lang="ts">
  import * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  // let { modelColor } = $props();

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Mesh_0: THREE.Mesh
    }
    materials: {
      Material_0: THREE.MeshPhysicalMaterial
    }
  }

  // let currentMaterial = $state<THREE.MeshPhysicalMaterial>();
  // Materiales pre-creados (evita recrearlos constantemente)
  const materials = {
    black: new THREE.MeshPhysicalMaterial({
      transmission: 1.0,
      thickness: 0.5,
      attenuationColor: new THREE.Color(0x050505),
      attenuationDistance: 5.5,
      roughness: 0.2
    }),
    white: new THREE.MeshPhysicalMaterial({
      transmission: 1.0,
      thickness: 0.5,
      attenuationColor: new THREE.Color(0xeeeeee),
      attenuationDistance: 5.5,
      roughness: 0.2
    }),
    gray: new THREE.MeshPhysicalMaterial({
      transmission: 1.0,
      thickness: 0.5,
      attenuationColor: new THREE.Color(0x444444),
      attenuationDistance: 5.5,
      roughness: 0.2
    }),
    translucent: new THREE.MeshPhysicalMaterial({
      transmission: 1.0,
      thickness: 0.1,
      attenuationColor: new THREE.Color(0x1015ff),
      attenuationDistance: 5.5,
      transparent: true,
      roughness: 0.1
    })
  };
  // const getMaterial = () => materials[modelColor as keyof typeof materials] || materials.translucent;

  const dracoLoader = useDraco();
  const gltf = useGltf<GLTFResult>('/models/mmoi2-transformed.glb', { dracoLoader });
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <!-- <T.Mesh
      geometry={gltf.nodes.Mesh_0.geometry}
      material={gltf.materials.Material_0}
      position={[0, -1, 0]}
      scale={[7, 7, 7]}
    /> -->
    <T.Mesh
      geometry={gltf.nodes.Mesh_0.geometry}
      material={materials.white}
      position={[0, -1, 0]}
      scale={[7, 7, 7]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
